### ISSUE TITLE
Pulseaudio core dump - armhf

### ISSUE THREAD

**Issue by grewhit25** [woahbase/alpine-pulseaudio#1] opened 2018-08-04 08:03 UTC
I tried running this image, "woahbase/alpine-pulseaudio:armhf", back in May 2018 on my Raspberry PI 3B but got Core Dump  when I tried sending audio to my BT device (details below). Same again today after downloading the latest image.

The problem seems to be related to: /usr/lib/libsbc.so.1.2.1
Could this be a fix?

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=856487
pulseaudio core dump
fixed in
Source: sbc
Source-Version: 1.3-2

Core Dump
``` text
sudo coredumpctl dump --output /tmp/core 03/05/2018
           PID: 17148 (pulseaudio)
           UID: 0 (root)
           GID: 0 (root)
        Signal: 11 (SEGV)
     Timestamp: Thu 2018-05-03 15:33:21 BST (23min ago)
  Command Line: /usr/bin/pulseaudio --log-level=1 --log-target=stderr --disallow-exit=true --exit-idle-time=180 -vvvv
    Executable: /usr/bin/pulseaudio
 Control Group: /system.slice/docker.service
          Unit: docker.service
         Slice: system.slice
       Boot ID: 5115baf9afd74990908b35d45f8c763d
    Machine ID: a3f6507858c04f0e9c7c78fae9a44f21
      Hostname: xxxxxx
       Storage: /var/lib/systemd/coredump/core.pulseaudio.0.5115baf9afd74990908b35d45f8c763d.17148.1525358001000000.lz4
       Message: Process 17148 (pulseaudio) of user 0 dumped core.

                Stack trace of thread 217:
                #0  0x00000000726dc534 n/a (/usr/lib/libsbc.so.1.2.1)

sudo coredumpctl dump --output /tmp/core 04/08/2018
           PID: 6183 (pulseaudio)
           UID: 0 (root)
           GID: 0 (root)
        Signal: 11 (SEGV)
     Timestamp: Sat 2018-08-04 08:31:00 BST (10min ago)
  Command Line: /usr/bin/pulseaudio --log-level=1 --log-target=stderr --disallow-exit=true --exit-idle-time=180 -vvvv
    Executable: /usr/bin/pulseaudio
 Control Group: /system.slice/docker.service
          Unit: docker.service
         Slice: system.slice
       Boot ID: 662c8828a9a541f4a47f893824851680
    Machine ID: a3f6507858c04f0e9c7c78fae9a44f21
      Hostname: xxxxxx
       Storage: /var/lib/systemd/coredump/core.pulseaudio.0.662c8828a9a541f4a47f893824851680.6183.1533367860000000.lz4
       Message: Process 6183 (pulseaudio) of user 0 dumped core.

                Stack trace of thread 217:
                #0  0x000000007264a534 n/a (/usr/lib/libsbc.so.1.2.1)
```

**Comment by lapnapra** [comment] 2019-06-17 13:37
Closing this one, cannot reproduce so I guess issue seems fixed now, and there hasn't been any activity since.

**Closed as completed by lapnapra** 2019-06-17 13:37 UTC
